bot:
  token: ${BOT_TOKEN}
  prefix: "mi!"
  useSharding: false
  shards: 1
  ownerIds:
    - ${OWNER_ID_1}

lavalink:
  nodes:
    - id: "Main"
      host: ${LAVALINK_NODE_1_HOST}
      port: ${LAVALINK_NODE_1_PORT}
      password: ${LAVALINK_NODE_1_PASSWORD}
      secure: true
  defaultSearchEngine: "ytsearch"
  autoPlay: false

cloudflare:
  zoneId: ${CF_ZONE_ID}
  apiToken: ${CF_API_TOKEN}

pterodactyl:
  url: ${PTERODACTYL_URL}
  apiKey: ${PTERODACTYL_API_KEY}

kubernetes:
  inCluster: ${K8S_IN_CLUSTER}